name: Test Liquibase Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Check Runner
        shell: 'C:\Program Files\Git\bin\bash.exe'
        run: |
          echo "======================================"
          echo "Runner Name : $RUNNER_NAME"
          echo "Runner OS   : $RUNNER_OS"
          echo "Runner Arch : $RUNNER_ARCH"
          echo "Workspace   : $GITHUB_WORKSPACE"
          echo "======================================"

      - name: Check Java
        shell: bash
        run: |
          java -version

      - name: Check Git
        shell: bash
        run: |
          git --version

      - name: Check Liquibase
        shell: bash
        run: |
          liquibase --version

      - name: Check Snowflake JDBC Driver
        shell: bash
        run: |
          JAR="/c/Users/AKSHATA RANI/liquibase_libs/snowflake-jdbc-4.3.2.jar"

          if [ -f "$JAR" ]; then
            echo "Snowflake JDBC driver found:"
            echo "$JAR"
          else
            echo "ERROR: Snowflake JDBC driver NOT found"
            exit 1
          fi
